### ISSUE TITLE
ios 出错

### ISSUE THREAD

**Issue by listenecho** [EatherToo/react-native-onepass-alibaba#1]
ExceptionsManager.js:180 Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]' was thrown while invoking setDialogUIConfig on target RNAliOnepass with params (
        {
        appPrivacyBaseColor = "#4F4F4F";
        appPrivacyColor = "#5B6FFF";
        appPrivacyOneName = " \U7528\U6237\U534f\U8bae ";
        appPrivacyOneUrl = "";
        appPrivacyTwoName = " \U9690\U79c1\U653f\U7b56 ";
        appPrivacyTwoUrl = "";
        checkboxHidden = 1;
        dialogHeightDelta = "110.4";
        lightColor = 1;
        logBtnBackgroundPath = "login_btn_bg";
        logBtnBackgroundPaths =         (
            "onepass_login_btn_normal",
            "onepass_login_btn_press",
            "onepass_login_btn_press"
        );
        logBtnMarginLeftAndRight = 30;
        logBtnText = "\U672c\U673a\U53f7\U7801\U4e00\U952e\U767b\U5f55";
        logBtnTextColor = "#FFFFFF";
        logBtnTextSize = 15;
        navColor = "#FFFFFF";
        navReturnImgPath = "back_icon";
        navText = "\U767b\U5f55";
        navTextColor = "#333333";
        navTextSize = 18;
        numberColor = "#333333";
        numberSize = 30;
        privacyBefore = "\U767b\U5f55\U5373\U4ee3\U8868\U5df2\U9605\U8bfb\U5e76\U540c\U610f";
        privacyEnd = "\U5e76\U6388\U6743\U83b7\U53d6\U672c\U673a\U53f7\U7801";
        privacyState = 1;
        privacyTextSize = 12;
        sloganOffsetY = "1.104";
        sloganText = "\U8ba4\U8bc1\U670d\U52a1\U7531\U4e2d\U56fd\U8054\U901a\U63d0\U4f9b";
        sloganTextColor = "#B2B2B2";
        sloganTextSize = 13;
        switchAccText = "\U5176\U4ed6\U767b\U5f55\U65b9\U5f0f";
        switchAccTextColor = "#666666";
        switchAccTextSize = 15;
        vendorPrivacyPrefix = "\U300a";
        vendorPrivacySuffix = "\U300b";
        webNavColor = "#FFFFFF";
        webNavTextColor = "#333333";
        webNavTextSize = 18;
    },
    7666,
    7667
)

ios 只是需要 pod install 吗
"react": "17.0.1",
"react-native": "0.64.0",
xcode Version 12.5.1 (12E507)
mac m1

**Comment by EatherToo** [comment]
> ExceptionsManager.js:180 Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]' was thrown while invoking setDialogUIConfig on target RNAliOnepass with params (
> {
> appPrivacyBaseColor = "#4F4F4F";
> appPrivacyColor = "#5B6FFF";
> appPrivacyOneName = " \U7528\U6237\U534f\U8bae ";
> appPrivacyOneUrl = "";
> appPrivacyTwoName = " \U9690\U79c1\U653f\U7b56 ";
> appPrivacyTwoUrl = "";
> checkboxHidden = 1;
> dialogHeightDelta = "110.4";
> lightColor = 1;
> logBtnBackgroundPath = "login_btn_bg";
> logBtnBackgroundPaths = (
> "onepass_login_btn_normal",
> "onepass_login_btn_press",
> "onepass_login_btn_press"
> );
> logBtnMarginLeftAndRight = 30;
> logBtnText = "\U672c\U673a\U53f7\U7801\U4e00\U952e\U767b\U5f55";
> logBtnTextColor = "#FFFFFF";
> logBtnTextSize = 15;
> navColor = "#FFFFFF";
> navReturnImgPath = "back_icon";
> navText = "\U767b\U5f55";
> navTextColor = "#333333";
> navTextSize = 18;
> numberColor = "#333333";
> numberSize = 30;
> privacyBefore = "\U767b\U5f55\U5373\U4ee3\U8868\U5df2\U9605\U8bfb\U5e76\U540c\U610f";
> privacyEnd = "\U5e76\U6388\U6743\U83b7\U53d6\U672c\U673a\U53f7\U7801";
> privacyState = 1;
> privacyTextSize = 12;
> sloganOffsetY = "1.104";
> sloganText = "\U8ba4\U8bc1\U670d\U52a1\U7531\U4e2d\U56fd\U8054\U901a\U63d0\U4f9b";
> sloganTextColor = "#B2B2B2";
> sloganTextSize = 13;
> switchAccText = "\U5176\U4ed6\U767b\U5f55\U65b9\U5f0f";
> switchAccTextColor = "#666666";
> switchAccTextSize = 15;
> vendorPrivacyPrefix = "\U300a";
> vendorPrivacySuffix = "\U300b";
> webNavColor = "#FFFFFF";
> webNavTextColor = "#333333";
> webNavTextSize = 18;
> },
> 7666,
> 7667
> )
> 
> ios 只是需要 pod install 吗
> "react": "17.0.1",
> "react-native": "0.64.0",
> xcode Version 12.5.1 (12E507)
> mac m1



可以提供一下setDialogUIConfig的参数吗

**Comment by EatherToo** [comment]
应该是某个参数插入的时候报错了

**Comment by listenecho** [comment]
```
await OnePass.setDialogUIConfig({
      // 弹窗高度
      dialogHeightDelta: px2dp(100),
      //状态栏
      lightColor: true,
      // 标题栏
      navColor: '#FFFFFF',
      navTextColor: '#333333',
      navText: '登录',
      navTextSize: 18,
      webNavColor: '#FFFFFF',
      webNavTextColor: '#333333',
      webNavTextSize: 18,
      navReturnImgPath: 'back_icon',
      // logo
      // logoImgPath: require('~assets/images/mine/logo.png'),
      // logoHidden: true,
      // logoWidth: 80,
      // logoHeight: 80,
      // logoOffsetY:  px2dp(50),
      // 手机号掩码
      numberColor: '#333333',
      numberSize: 30,
      // numberFieldOffsetY: 30,
      // numberFieldOffsetY: getOffsetY(200),
      // slogan
      sloganText: `认证服务由${operatorType}提供`,
      sloganTextColor: '#B2B2B2',
      sloganTextSize: 13,
      sloganOffsetY: px2dp(1),
      // sloganOffsetY: getOffsetY(248),
      // 登录按钮
      logBtnText: '本机号码一键登录',
      logBtnTextColor: '#FFFFFF',
      logBtnTextSize: 15,
      // logBtnHeight: 40,
      // ios
      logBtnBackgroundPaths: [
          'onepass_login_btn_normal',
          'onepass_login_btn_press',
          'onepass_login_btn_press',
      ],
      // android
      logBtnBackgroundPath: 'login_btn_bg',
      logBtnMarginLeftAndRight: 30,
      // logBtnOffsetY: px2dp(90),
      // 其他登录方式
      // switchAccHidden: true,
      switchAccText: '其他登录方式',
      switchAccTextSize: 15,
      switchAccTextColor: '#666666',
      // switchOffsetY: px2dp(150),
      // 协议栏
      privacyBefore: '登录即代表已阅读并同意',
      privacyEnd: '并授权获取本机号码',
      checkboxHidden: true,
      privacyState: true,
      appPrivacyOneName: ' 用户协议 ',
      appPrivacyOneUrl: APP.userAgrenn,
      appPrivacyTwoName: ' 隐私政策 ',
      appPrivacyTwoUrl: APP.private,
      vendorPrivacyPrefix: '《',
      vendorPrivacySuffix: '》',
      privacyTextSize: 12,
      appPrivacyBaseColor: '#4F4F4F',
      appPrivacyColor: '#5B6FFF',
  })
```

**Comment by listenecho** [comment]
ts 类型没报错，最开始的配置是按照你fork的那个库来的

**Comment by listenecho** [comment]
我在安卓上能成功使用

**Comment by EatherToo** [comment]
> ts 类型没报错，最开始的配置是按照你fork的那个库来的

我尝试复现一下

**Comment by listenecho** [comment]
麻烦你了

**Comment by listenecho** [comment]
麻烦你了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月5日(星期四) 下午4:35
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [EatherToo/react-native-onepass-alibaba] ios 出错 (#1)





  
ts 类型没报错，最开始的配置是按照你fork的那个库来的
  
我尝试复现一下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EatherToo** [comment]
> 麻烦你了

bug已找到
```
 logBtnBackgroundPaths: [
      'onepass_login_btn_normal',
      'onepass_login_btn_press',
      'onepass_login_btn_press',
    ],
```
这个参数有问题，你本地没有这三张图片，所以报错了

**Comment by listenecho** [comment]
这个图片可以不设置吗

**Comment by EatherToo** [comment]
> 这个图片可以不设置吗

可以

**Comment by listenecho** [comment]
调起来了，太感谢大佬了。
