### ISSUE TITLE
AppID Secret解析失败

### ISSUE THREAD

**Issue by kinger906** [EatherToo/react-native-onepass-alibaba#2]
Error: {"carrierFailedResultData":"","code":"600017","msg":"AppID Secret解析失败","requestCode":0,"requestId":"1b209418-fc26-4946-8add-d940d889a839","vendorName":"CTCC"}

**Comment by EatherToo** [comment]
> 
关于这个报错码可以去阿里云官网看一下具体信息

**Comment by EatherToo** [comment]
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/22785612/156128681-9d451542-ce27-4e2c-9380-218c64c4f6ad.png">

[官方说明](https://help.aliyun.com/document_detail/409830.html?spm=5176.21213303.J_6704733920.7.40a653c9wLqEqu&scm=20140722.S_help%40%40%E6%96%87%E6%A1%A3%40%40409830.S_os%2Bhot.ID_409830-RL_600017-LOC_helpmain-OR_ser-V_2-P0_0)
